# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role_auditlog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profil_utilisateur',
        ),
    ]
