# Generated by Django 5.2.11 on 2026-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_table_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'droit',
                'ordering': ['ordre', 'label'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='droits',
            field=models.ManyToManyField(blank=True, related_name='profils', to='accounts.droit'),
        ),
    ]
