# Generated by Django 5.2.11 on 2026-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secteurs', '0006_alter_secteur_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(blank=True, max_length=120)),
                ('matricule', models.CharField(blank=True, max_length=40)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_terrain', to='secteurs.secteur')),
            ],
            options={
                'db_table': 'agent_terrain',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
