# Generated by Django 5.2.11 on 2026-06-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_superviseurgeneral_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentterrain',
            name='code',
        ),
    ]
