# Generated by Django 5.2.11 on 2026-04-11

from django.db import migrations


def drop_ia_tables(apps, schema_editor):
    # Suppression definitive des tables IA (le module ia n'est plus utilise)
    tables = [
        "ia_parametreia",
        "ia_predictionscenario",
        "ia_anomalie",
    ]

    cascade = " CASCADE" if schema_editor.connection.vendor == "postgresql" else ""
    for table in tables:
        schema_editor.execute(f"DROP TABLE IF EXISTS {table}{cascade};")


class Migration(migrations.Migration):

    dependencies = [
        ("recoltes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(drop_ia_tables, migrations.RunPython.noop),
    ]
