# Generated by Django 5.2.11 on 2026-04-11

from django.db import migrations


def drop_paiements_tables(apps, schema_editor):
    # Suppression definitive des tables Paiements (module retire)
    tables = [
        "paiements_paiement",
    ]

    cascade = " CASCADE" if schema_editor.connection.vendor == "postgresql" else ""
    for table in tables:
        schema_editor.execute(f"DROP TABLE IF EXISTS {table}{cascade};")


class Migration(migrations.Migration):

    dependencies = [
        ("recoltes", "0002_drop_ia_tables"),
    ]

    operations = [
        migrations.RunPython(drop_paiements_tables, migrations.RunPython.noop),
    ]
