# Generated by Django 5.2.11 on 2026-05-29 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0006_drop_remaining_paiements_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecolte',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_recolte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficherecolte',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
    ]
