# Generated by Django 5.2.11 on 2026-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0007_ficherecolte_created_by_ficherecolte_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecolte',
            name='conditions_meteo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolte',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolte',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolte',
            name='nb_palmiers_recoltes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolte',
            name='surface_recoltee_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ficherecoltedetail',
            name='coordonnees_GPS_palmier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ficherecoltedetail',
            name='qualite_regime',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolteligne',
            name='nb_heures_travail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolteligne',
            name='prime_qualite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ficherecolteligne',
            name='salaire_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ficherecuvente',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('espece', 'Espèce'), ('virement', 'Virement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ficherecuvente',
            name='reference_facture',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='ficherecuvente',
            name='vehicule_transport',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='superviseuradjoint',
            name='matricule',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='superviseuradjoint',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
