# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0009_alter_ficherecolteligne_recolteur'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ficherecolte',
            table='fiche_recolte',
        ),
        migrations.AlterModelTable(
            name='ficherecoltedetail',
            table='detail_recolte',
        ),
        migrations.AlterModelTable(
            name='ficherecolteligne',
            table='ligne_recolte',
        ),
        migrations.AlterModelTable(
            name='ficherecuvente',
            table='recu_vente',
        ),
        migrations.AlterModelTable(
            name='superviseuradjoint',
            table='superviseur_adjoint',
        ),
    ]
