# Generated by Django 5.2.11 on 2026-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0010_alter_ficherecolte_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecolte',
            name='depense_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
