# Generated by Django 5.2.11 on 2026-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0011_ficherecolte_depense_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecolte',
            name='depense_salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
