# Generated by Django 5.2.11 on 2026-06-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0012_ficherecolte_depense_salaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client',
                'ordering': ['nom'],
            },
        ),
    ]
