# Generated by Django 5.2.11 on 2026-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('recoltes', '0014_add_validated_by_at_to_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='superviseuradjoint',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_participees', to='agents.agentterrain'),
        ),
    ]
