# Generated by Django 5.2.11 on 2026-06-09 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_add_superviseur_general'),
        ('recoltes', '0015_superviseuradjoint_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficherecolte',
            name='superviseur_general_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_supervisees', to='agents.superviseurgeneral'),
        ),
    ]
