# Generated by Django 5.2.11 on 2026-06-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0016_fiche_fk_superviseur_general'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_non_conformes', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('montant_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parametre_bonus',
            },
        ),
        migrations.AlterModelOptions(
            name='ficherecuvente',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='ficherecuvente',
            name='client_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recus', to='recoltes.client'),
        ),
        migrations.AddField(
            model_name='ficherecuvente',
            name='prix_officiel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
