# Generated by Django 5.2.11 on 2026-06-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoltes', '0017_add_prix_officiel_client_obj_parametre_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validation', 'Validation fiche'), ('rejet', 'Rejet fiche'), ('modification_fiche', 'Modification fiche'), ('modification_bareme', 'Modification barème'), ('prix_officiel', 'Saisie/modif prix officiel'), ('modification_recu', 'Modification reçu de vente'), ('suppression_recu', 'Suppression reçu de vente')], max_length=40)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('fiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='recoltes.ficherecolte')),
                ('recu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='recoltes.ficherecuvente')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_subies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
