# Generated by Django 5.2.11 on 2026-04-01 00:00

from decimal import Decimal
from django.db import migrations


def fill_superficie(apps, schema_editor):
    Secteur = apps.get_model("secteurs", "Secteur")
    mapping = {
        "GP_1": Decimal("7.47"),
        "GP_2": Decimal("4.60"),
        "RTE_BOUB": Decimal("1.90"),
        "PM_1": Decimal("3.48"),
        "PM_2": Decimal("4.44"),
        "JC_1": Decimal("6.80"),
        "JC_2": Decimal("1.17"),
        "CO": Decimal("2.07"),
        "AA": Decimal("2.67"),
    }

    for code, superficie in mapping.items():
        (
            Secteur.objects.filter(code=code)
            .filter(superficie_ha__isnull=True)
            .update(superficie_ha=superficie)
        )
        (
            Secteur.objects.filter(code=code)
            .filter(superficie_ha=0)
            .update(superficie_ha=superficie)
        )


def reverse_fill(apps, schema_editor):
    # Pas de rollback automatique
    return


class Migration(migrations.Migration):

    dependencies = [
        ("secteurs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_superficie, reverse_fill),
    ]
