# Generated by Django 5.2.11 on 2026-04-11

from decimal import Decimal

from django.db import migrations, models


def fill_plantation_info(apps, schema_editor):
    Secteur = apps.get_model("secteurs", "Secteur")
    mapping = {
        "GP_1": {"superficie": Decimal("7.47"), "relief": "Plateau", "sol": "Sableux / Argileux"},
        "GP_2": {"superficie": Decimal("4.60"), "relief": "Plateau / Pentus", "sol": "Argileux / Gravillonnaire"},
        "RTE_BOUB": {"superficie": Decimal("1.90"), "relief": "Plateau", "sol": "Argileux"},
        "PM_1": {"superficie": Decimal("3.48"), "relief": "Plateau / Pentus", "sol": "Gravillonnaire / Argileux / Sableux"},
        "PM_2": {"superficie": Decimal("4.44"), "relief": "Pentus - Plateau", "sol": "Humifere - Argileux"},
        "JC_1": {"superficie": Decimal("6.80"), "relief": "Pentus - Plateau", "sol": "Sableux - Humifere"},
        "JC_2": {"superficie": Decimal("1.17"), "relief": "Plateau", "sol": "Sableux"},
        "CO": {"superficie": Decimal("2.07"), "relief": "Plateau", "sol": "Argileux - Gravillonnaire"},
        "AA": {"superficie": Decimal("2.67"), "relief": "Plateau", "sol": "Sableux - Argileux"},
    }

    for code, info in mapping.items():
        qs = Secteur.objects.filter(code=code)
        for secteur in qs:
            changed = []
            if secteur.superficie_ha in (None, 0):
                secteur.superficie_ha = info["superficie"]
                changed.append("superficie_ha")
            if not (secteur.situation_relief or "").strip():
                secteur.situation_relief = info["relief"]
                changed.append("situation_relief")
            if not (secteur.type_sol or "").strip():
                secteur.type_sol = info["sol"]
                changed.append("type_sol")
            if changed:
                secteur.save(update_fields=changed)

    # Fallback: evite les valeurs NULL avant le passage en non-null
    Secteur.objects.filter(superficie_ha__isnull=True).update(superficie_ha=Decimal("0.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("secteurs", "0002_fill_superficie_ha"),
    ]

    operations = [
        migrations.AddField(
            model_name="secteur",
            name="annee_plantation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secteur",
            name="situation_relief",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="secteur",
            name="type_sol",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(fill_plantation_info, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="secteur",
            name="superficie_ha",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.RemoveField(
            model_name="secteur",
            name="actif",
        ),
        migrations.RemoveField(
            model_name="secteur",
            name="responsable",
        ),
    ]
