# Generated by Django 5.2.11 on 2026-04-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0003_align_secteur_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteur',
            name='annee_plantation',
        ),
    ]
