# Generated by Django 5.2.11 on 2026-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0004_remove_secteur_annee_plantation'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='age_moyen_plants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='coordonnees_GPS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='nb_palmiers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='rendement_cible_t_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='secteur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10),
        ),
    ]
