# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0005_secteur_age_moyen_plants_secteur_coordonnees_gps_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secteur',
            table='secteur',
        ),
    ]
