// Endpoints API (DRF)
export const endpoints = {
  secteurs: "/secteurs/",
  personnel: "/personnel/",
  recolteurs: "/personnel/",
  recoltes: "/recoltes/",
  travaux: "/travaux/",
  materiels: "/materiels/",
  materielsUtilises: "/materiels-utilises/",
  users: "/users/",
  superviseurs: "/superviseurs-generaux/",
  audit: "/audit/",
  agents: "/agents/",
  droits: "/droits/",
  iaModeles: "/ia/modeles/",
  iaPredictions: "/ia/predictions/",
  iaAnomalies: "/ia/anomalies/",
  iaMeteo: "/ia/meteo/",
  iaSynthese: "/ia/synthese/",
  iaSimulation: "/ia/simulation/",
  iaPrescriptions: "/ia/prescriptions/",
  iaEntrainer: "/ia/entrainer/",
  iaPredire: "/ia/predire-rendement/",
  iaDetecter: "/ia/detecter-anomalie/",
};
