# Generated by Django 5.2.11 on 2026-04-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoltes', '0004_remove_paye_amount'),
        ('recolteurs', '0005_recolteur_code_short_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recolteur_nom', models.CharField(blank=True, max_length=120)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Paye'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('regimes_grands', models.PositiveIntegerField(default=0)),
                ('regimes_moyens', models.PositiveIntegerField(default=0)),
                ('regimes_petits', models.PositiveIntegerField(default=0)),
                ('total_regimes', models.PositiveIntegerField(default=0)),
                ('montant_fcfa', models.PositiveIntegerField(default=0)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='recoltes.ficherecolte')),
                ('recolteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='recolteurs.recolteur')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fiche', 'recolteur'), name='uniq_paiement_fiche_recolteur'), models.UniqueConstraint(condition=models.Q(('recolteur__isnull', True)), fields=('fiche', 'recolteur_nom'), name='uniq_paiement_fiche_recolteur_nom_null')],
            },
        ),
    ]
