# Generated by Django 5.2.11 on 2026-05-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0002_fichetravaux_created_by_fichetravaux_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetravaux',
            name='nature_travaux',
            field=models.CharField(blank=True, choices=[('desherbage', 'Désherbage'), ('traitement_phytosanitaire', 'Traitement phytosanitaire'), ('fertilisation', 'Fertilisation'), ('taille_ablation', 'Taille / Ablation'), ('recolte', 'Récolte'), ('pepiniere', 'Pépinière'), ('plantation', 'Plantation'), ('entretien_voie', "Entretien voie d'accès"), ('entretien_infrastructure', 'Entretien infrastructure'), ('recensement', 'Recensement'), ('autre', 'Autre')], max_length=50),
        ),
    ]
