# Generated by Django 5.2.11 on 2026-06-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_materielequipement_categorie_and_more'),
        ('travaux', '0003_nature_travaux_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommabletravaux',
            name='date_peremption',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommabletravaux',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='consommabletravaux',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='cout_total_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='materiels_utilises',
            field=models.ManyToManyField(blank=True, related_name='fiches_travaux', through='materiels.MaterielUtiliseTravaux', to='materiels.materielequipement'),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='statut_avancement',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20),
        ),
        migrations.AddField(
            model_name='fichetravaux',
            name='type_travaux',
            field=models.CharField(blank=True, choices=[('desherbage', 'Désherbage'), ('traitement', 'Traitement'), ('fertilisation', 'Fertilisation'), ('taille', 'Taille'), ('recolte', 'Récolte'), ('pepiniere', 'Pépinière'), ('plantation', 'Plantation'), ('entretien_voie', 'Entretien voie'), ('entretien_infra', 'Entretien infrastructure'), ('recensement', 'Recensement'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repartitiontache',
            name='matricule_ouvrier',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='repartitiontache',
            name='salaire_total_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
