# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secteurs', '0006_alter_secteur_table'),
        ('travaux', '0004_consommabletravaux_date_peremption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetravaux',
            name='secteurs_couverts',
            field=models.ManyToManyField(blank=True, db_table='fiche_travaux_secteur', related_name='fiches_travaux', to='secteurs.secteur'),
        ),
        migrations.AlterModelTable(
            name='consommabletravaux',
            table='consommable_travaux',
        ),
        migrations.AlterModelTable(
            name='fichetravaux',
            table='fiche_travaux',
        ),
        migrations.AlterModelTable(
            name='repartitiontache',
            table='repartition_tache',
        ),
    ]
