# Generated by Django 5.2.11 on 2026-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travaux', '0006_fichetravaux_validated_by_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetravaux',
            name='salaire_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
