# Generated by Django 5.2.11 on 2026-06-05 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0001_initial'),
        ('travaux', '0003_nature_travaux_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielequipement',
            name='categorie',
            field=models.CharField(blank=True, choices=[('vehicule', 'Véhicule'), ('outil', 'Outil'), ('equipement_lourd', 'Équipement lourd'), ('petit_materiel', 'Petit matériel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='date_derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='date_prochaine_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='localisation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='responsable',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='materielequipement',
            name='valeur_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='MaterielUtiliseTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=1)),
                ('observations', models.TextField(blank=True)),
                ('fiche_travaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_utilises_detail', to='travaux.fichetravaux')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_travaux', to='materiels.materielequipement')),
            ],
            options={
                'verbose_name': 'Matériel utilisé (travaux)',
                'verbose_name_plural': 'Matériels utilisés (travaux)',
                'unique_together': {('materiel', 'fiche_travaux')},
            },
        ),
    ]
