# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_materielequipement_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materielequipement',
            table='materiel',
        ),
        migrations.AlterModelTable(
            name='materielutilisetravaux',
            table='materiel_travaux',
        ),
    ]
