# Generated by Django 5.2.11 on 2026-07-28 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secteurs', '0006_alter_secteur_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotSemence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(blank=True, max_length=30, unique=True)),
                ('variete', models.CharField(max_length=120)),
                ('fournisseur', models.CharField(blank=True, max_length=160)),
                ('origine', models.CharField(blank=True, max_length=160)),
                ('certification', models.CharField(blank=True, max_length=160)),
                ('date_acquisition', models.DateField()),
                ('date_mise_en_germination', models.DateField(blank=True, null=True)),
                ('nombre_graines', models.PositiveIntegerField(default=0)),
                ('nombre_graines_germees', models.PositiveIntegerField(blank=True, null=True)),
                ('taux_germination', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('acquis', 'Acquis'), ('germination', 'En germination'), ('pepiniere', 'En pepiniere'), ('epuise', 'Epuise'), ('rejete', 'Rejete')], default='acquis', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_semences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lot_semence',
                'ordering': ['-date_acquisition', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LotPepiniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_entree', models.DateField()),
                ('date_sortie_prevue', models.DateField(blank=True, null=True)),
                ('date_sortie_reelle', models.DateField(blank=True, null=True)),
                ('nombre_plants_initial', models.PositiveIntegerField(default=0)),
                ('nombre_plants_valides', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_plants_rejetes', models.PositiveIntegerField(default=0)),
                ('nombre_plants_morts', models.PositiveIntegerField(default=0)),
                ('taille_moyenne_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nombre_feuilles_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('etat_sanitaire', models.CharField(blank=True, max_length=160)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('pret', 'Pret a planter'), ('plante', 'Plante'), ('rejete', 'Rejete')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_pepinieres', to=settings.AUTH_USER_MODEL)),
                ('lot_semence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_pepinieres', to='plantations.lotsemence')),
            ],
            options={
                'db_table': 'lot_pepiniere',
                'ordering': ['-date_entree', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationPlantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_operation', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_plantation', models.DateField()),
                ('nombre_plants', models.PositiveIntegerField(default=0)),
                ('densite_plantation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ecartement_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_plants_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('plants_remplaces', models.PositiveIntegerField(default=0)),
                ('conditions_meteo', models.CharField(blank=True, max_length=160)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiee'), ('realisee', 'Realisee'), ('suivi', 'En suivi'), ('cloturee', 'Cloturee')], default='realisee', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_plantation', to=settings.AUTH_USER_MODEL)),
                ('lot_pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_plantation', to='plantations.lotpepiniere')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_plantation', to='secteurs.secteur')),
            ],
            options={
                'db_table': 'operation_plantation',
                'ordering': ['-date_plantation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ObservationSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField()),
                ('type_probleme', models.CharField(max_length=160)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Elevee'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('surface_touchee_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('action_recommandee', models.TextField(blank=True)),
                ('action_effectuee', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_traitement', 'En traitement'), ('resolue', 'Resolue'), ('surveillance', 'Surveillance')], default='nouvelle', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_sanitaires', to='secteurs.secteur')),
                ('operation_plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_sanitaires', to='plantations.operationplantation')),
            ],
            options={
                'db_table': 'observation_sanitaire',
                'ordering': ['-date_observation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SuiviCroissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField()),
                ('hauteur_moyenne_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nombre_feuilles_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mortalite', models.PositiveIntegerField(default=0)),
                ('plants_remplaces', models.PositiveIntegerField(default=0)),
                ('stress_hydrique', models.BooleanField(default=False)),
                ('etat_general', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('faible', 'Faible'), ('critique', 'Critique')], default='bon', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_plantation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_croissance', to='plantations.operationplantation')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_croissance', to='secteurs.secteur')),
            ],
            options={
                'db_table': 'suivi_croissance',
                'ordering': ['-date_observation', '-id'],
                'unique_together': {('secteur', 'date_observation')},
            },
        ),
        migrations.CreateModel(
            name='SuiviPepiniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observation', models.DateField()),
                ('nombre_plants_vivants', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_plants_morts', models.PositiveIntegerField(default=0)),
                ('taille_moyenne_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nombre_feuilles_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arrosage', models.CharField(blank=True, max_length=120)),
                ('fertilisation', models.CharField(blank=True, max_length=160)),
                ('maladie', models.CharField(blank=True, max_length=160)),
                ('ravageurs', models.CharField(blank=True, max_length=160)),
                ('etat_sanitaire', models.CharField(blank=True, max_length=160)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot_pepiniere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='plantations.lotpepiniere')),
            ],
            options={
                'db_table': 'suivi_pepiniere',
                'ordering': ['-date_observation', '-id'],
                'unique_together': {('lot_pepiniere', 'date_observation')},
            },
        ),
    ]
