# Generated by Django 5.2.11 on 2026-04-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoltes', '0004_remove_paye_amount'),
        ('recolteurs', '0005_recolteur_code_short_format'),
        ('secteurs', '0004_remove_secteur_annee_plantation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(default='seasonal_linear_v1', max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('horizon_months', models.PositiveIntegerField(default=6)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('predictions', models.JSONField(blank=True, default=list)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_scenarios', to='secteurs.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=80)),
                ('niveau', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Eleve')], default='moyen', max_length=10)),
                ('metric', models.CharField(blank=True, max_length=80)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('expected_min', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('expected_max', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('fiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='recoltes.ficherecolte')),
                ('recolteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='recolteurs.recolteur')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='secteurs.secteur')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'type'], name='ia_anomalie_year_9d7b5d_idx'), models.Index(fields=['resolved'], name='ia_anomalie_resolve_711f00_idx')],
            },
        ),
    ]
