# Generated by Django 5.2.11 on 2026-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_module', '0002_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='criticite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=10),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='methode_detection',
            field=models.CharField(choices=[('regles_metier', 'Règles métier'), ('isolation_forest', 'Isolation Forest'), ('decision_tree', 'Arbre de décision'), ('logistic_regression', 'Régression logistique')], default='regles_metier', max_length=30),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='statut',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='nouvelle', max_length=10),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type_anomalie',
            field=models.CharField(choices=[('recolte', 'Anomalie récolte'), ('rendement', 'Anomalie rendement'), ('recolteur', 'Anomalie récolteur'), ('poids', 'Anomalie poids/régimes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modeleia',
            name='algorithme',
            field=models.CharField(choices=[('linear_regression', 'Régression Linéaire'), ('random_forest', 'Random Forest Regressor'), ('decision_tree', 'Arbre de Décision'), ('logistic_regression', 'Régression Logistique'), ('isolation_forest', 'Isolation Forest')], max_length=40),
        ),
        migrations.AlterField(
            model_name='modeleia',
            name='type_tache',
            field=models.CharField(choices=[('regression', 'Régression (prédiction rendement)'), ('classification', 'Classification (anomalie supervisée)'), ('anomalie', "Détection d'anomalies (non supervisée)")], max_length=20),
        ),
    ]
