# Generated by Django 5.2.11 on 2026-07-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_module', '0003_alter_anomalie_criticite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='methode_detection',
            field=models.CharField(choices=[('regles_metier', 'Règles métier'), ('isolation_forest', 'Isolation Forest'), ('decision_tree', 'Arbre de décision'), ('logistic_regression', 'Régression logistique'), ('residu_prediction', 'Résidu du modèle de prédiction')], default='regles_metier', max_length=30),
        ),
    ]
