# Generated by Django 5.2.11 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recolteurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recolteur",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="recolteur",
            name="lieu_residence",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
