# Generated by Django 5.2.11 on 2026-04-11

from django.db import migrations, models


def fill_missing_fields(apps, schema_editor):
    Recolteur = apps.get_model("recolteurs", "Recolteur")
    for r in Recolteur.objects.all().only("id", "code", "lieu_residence"):
        updates = []
        if not r.code:
            r.code = f"REC-{r.id:06d}"
            updates.append("code")
        if not (r.lieu_residence or "").strip():
            r.lieu_residence = "N/A"
            updates.append("lieu_residence")
        if updates:
            r.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("recolteurs", "0002_recolteur_code_lieu_residence"),
    ]

    operations = [
        migrations.RunPython(fill_missing_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recolteur",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="recolteur",
            name="lieu_residence",
            field=models.CharField(max_length=120),
        ),
        migrations.RemoveField(
            model_name="recolteur",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="recolteur",
            name="secteur",
        ),
        migrations.RemoveField(
            model_name="recolteur",
            name="statut",
        ),
    ]
