# Generated by Django 5.2.11 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recolteurs", "0003_align_recolteur_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recolteur",
            name="code",
            field=models.CharField(
                max_length=20,
                unique=True,
                blank=True,
                null=True,
                editable=False,
            ),
        ),
    ]

