# Generated by Django 5.2.11 on 2026-04-11

from django.db import migrations


def reformat_codes(apps, schema_editor):
    Recolteur = apps.get_model("recolteurs", "Recolteur")
    qs = Recolteur.objects.all().only("id", "code")
    for r in qs:
        current = (r.code or "").strip()
        # On reformate uniquement nos codes (ou code vide) pour eviter d'ecraser un code "metier" existant.
        if not current or current.startswith("REC-"):
            new_code = f"REC-{r.id:03d}"
            if current != new_code:
                Recolteur.objects.filter(pk=r.pk).update(code=new_code)


class Migration(migrations.Migration):

    dependencies = [
        ("recolteurs", "0004_recolteur_code_autogen"),
    ]

    operations = [
        migrations.RunPython(reformat_codes, migrations.RunPython.noop),
    ]

