# Generated by Django 5.2.11 on 2026-05-29 01:01 (modifié pour gérer les données existantes)

from django.db import migrations, models


def assign_temp_phones(apps, schema_editor):
    """Assigne un numéro provisoire unique aux récolteurs sans numéro de téléphone."""
    Recolteur = apps.get_model("recolteurs", "Recolteur")
    for r in Recolteur.objects.filter(numero_telephone=""):
        r.numero_telephone = f"TEMP-{r.pk:05d}"
        r.save(update_fields=["numero_telephone"])


class Migration(migrations.Migration):

    dependencies = [
        ("recolteurs", "0005_recolteur_code_short_format"),
    ]

    operations = [
        # 1. Supprimer l'ancien champ code
        migrations.RemoveField(
            model_name="recolteur",
            name="code",
        ),
        # 2. Ajouter les nouveaux champs booléens et texte (sans contrainte unique sur le téléphone)
        migrations.AddField(
            model_name="recolteur",
            name="est_mobile_money",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recolteur",
            name="est_wave",
            field=models.BooleanField(default=False),
        ),
        # numero_telephone : d'abord sans unique pour permettre la migration des données
        migrations.AddField(
            model_name="recolteur",
            name="numero_telephone",
            field=models.CharField(blank=True, max_length=20, default=""),
        ),
        migrations.AddField(
            model_name="recolteur",
            name="numero_whatsapp",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="recolteur",
            name="operateur_mm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("orange_money", "Orange Money"),
                    ("mtn_momo", "MTN MoMo"),
                    ("moov_money", "Moov Money"),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recolteur",
            name="whatsapp_actif",
            field=models.BooleanField(default=False),
        ),
        # 3. Remplir les numéros provisoires pour les enregistrements existants
        migrations.RunPython(assign_temp_phones, migrations.RunPython.noop),
        # 4. Ajouter la contrainte unique maintenant que tous les enregistrements ont une valeur
        migrations.AlterField(
            model_name="recolteur",
            name="numero_telephone",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
