# Generated by Django 5.2.11 on 2026-06-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recolteurs', '0007_rename_recolteur_to_personnel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personnel',
            table='personnel',
        ),
    ]
