# Generated by Django 5.2.11 on 2026-06-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recolteurs', '0008_alter_personnel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='est_mobile_money',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='numero_whatsapp',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='operateur_mm',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='telephone',
        ),
    ]
